#! /usr/bin/python3
# -*- coding: utf-8 -*-
"""Created on Fri May 10 03:47:45 UTC+8:00 2019
    镜像器用于存储稳定的数据, OD镜像器
written by pyGlenn.
"""


class CorpODMirror:
    """OD镜像器
    """
    def __init__(self):
        self.logger: any = None  # 日志记录器
        # # # 国家三字码
        self._country_code = [
            {"country": "Australia","cityCode": "ADL","cityName": "Adelaide"},
            {"country": "Indonesia","cityCode": "ARD","cityName": "Alor Island"},
            {"country": "Malaysia","cityCode": "AOR","cityName": "Alor Setar"},
            {"country": "Indonesia","cityCode": "AMQ","cityName": "Ambon"},
            {"country": "Indonesia","cityCode": "VPM","cityName": "Ampana"},
            {"country": "India","cityCode": "ATQ","cityName": "Amritsar"},
            {"country": "Netherlands","cityCode": "AMS","cityName": "Amsterdam"},
            {"country": "Indonesia","cityCode": "LMU","cityName": "Anambas  "},
            {"country": "Indonesia","cityCode": "ABU","cityName": "Atambua"},
            {"country": "Indonesia","cityCode": "BJW","cityName": "Bajawa"},
            {"country": "Indonesia","cityCode": "DPS","cityName": "Bali"},
            {"country": "Indonesia","cityCode": "BPN","cityName": "Balikpapan"},
            {"country": "Indonesia","cityCode": "BTJ","cityName": "Banda Aceh"},
            {"country": "Indonesia","cityCode": "TKG","cityName": "Bandar Lampung"},
            {"country": "Indonesia","cityCode": "BDO","cityName": "Bandung"},
            {"country": "India","cityCode": "BLR","cityName": "Bangalore"},
            {"country": "Thailand","cityCode": "DMK","cityName": "Bangkok"},
            {"country": "Indonesia","cityCode": "BDJ","cityName": "Banjarmasin"},
            {"country": "Indonesia","cityCode": "BWX","cityName": "Banyuwangi"},
            {"country": "Indonesia","cityCode": "BTH","cityName": "Batam"},
            {"country": "Indonesia","cityCode": "BTW","cityName": "Batu Licin"},
            {"country": "Indonesia","cityCode": "BUW","cityName": "Baubau"},
            {"country": "Indonesia","cityCode": "BKS","cityName": "Bengkulu"},
            {"country": "Indonesia","cityCode": "BEJ","cityName": "Berau"},
            {"country": "Indonesia","cityCode": "BMU","cityName": "Bima"},
            {"country": "Australia","cityCode": "BNE","cityName": "Brisbane"},
            {"country": "Indonesia","cityCode": "WUB","cityName": "Buli"},
            {"country": "Indonesia","cityCode": "UOL","cityName": "Buol"},
            {"country": "China","cityCode": "CSX","cityName": "Changsha"},
            {"country": "China","cityCode": "CTU","cityName": "Chengdu"},
            {"country": "India","cityCode": "MAA","cityName": "Chennai"},
            {"country": "Thailand","cityCode": "CNX","cityName": "Chiang Mai"},
            {"country": "Thailand","cityCode": "CEI","cityName": "Chiang Rai"},
            {"country": "Bangladesh","cityCode": "CGP","cityName": "Chittagong"},
            {"country": "China","cityCode": "CKG","cityName": "Chongqing"},
            {"country": "Indonesia","cityCode": "CXP","cityName": "Cilacap"},
            {"country": "Sri Lanka","cityCode": "CMB","cityName": "Colombo"},
            {"country": "Denmark","cityCode": "CPH","cityName": "Copenhagen"},
            {"country": "Vietnam","cityCode": "DAD","cityName": "Da Nang"},
            {"country": "India","cityCode": "DEL","cityName": "Delhi"},
            {"country": "Bangladesh","cityCode": "DAC","cityName": "Dhaka"},
            {"country": "Indonesia","cityCode": "DOB","cityName": "Dobo"},
            {"country": "Indonesia","cityCode": "DUM","cityName": "Dumai"},
            {"country": "Indonesia","cityCode": "ENE","cityName": "Ende"},
            {"country": "Indonesia","cityCode": "FKQ","cityName": "Fak Fak"},
            {"country": "Germany","cityCode": "FRA","cityName": "Frankfurt"},
            {"country": "Indonesia","cityCode": "GLX","cityName": "Galela"},
            {"country": "Indonesia","cityCode": "GTO","cityName": "Gorontalo"},
            {"country": "China","cityCode": "CAN","cityName": "Guangzhou"},
            {"country": "China","cityCode": "KWL","cityName": "Guilin"},
            {"country": "China","cityCode": "KWE","cityName": "Guiyang"},
            {"country": "Indonesia","cityCode": "GNS","cityName": "Gunungsitoli"},
            {"country": "China","cityCode": "HAK","cityName": "Haikou"},
            {"country": "China","cityCode": "HGH","cityName": "Hangzhou"},
            {"country": "Vietnam","cityCode": "HAN","cityName": "Hanoi"},
            {"country": "Thailand","cityCode": "HDY","cityName": "Hat Yai"},
            {"country": "China","cityCode": "HFE","cityName": "Hefei"},
            {"country": "Vietnam","cityCode": "SGN","cityName": "Ho Chi Minh City"},
            {"country": "Hong Kong","cityCode": "HKG","cityName": "Hong Kong[SAR]"},
            {"country": "Malaysia","cityCode": "IPH","cityName": "Ipoh"},
            {"country": "Turkey","cityCode": "IST","cityName": "Istanbul"},
            {"country": "Indonesia","cityCode": "CGK","cityName": "Jakarta"},
            {"country": "Indonesia","cityCode": "HLP","cityName": "Jakarta"},
            {"country": "Indonesia","cityCode": "DJB","cityName": "Jambi"},
            {"country": "Indonesia","cityCode": "DJJ","cityName": "Jayapura"},
            {"country": "Indonesia","cityCode": "JBB","cityName": "Jember"},
            {"country": "China","cityCode": "TNA","cityName": "Jinan"},
            {"country": "Malaysia","cityCode": "JHB","cityName": "Johor Bahru"},
            {"country": "Indonesia","cityCode": "KNG","cityName": "Kaimana"},
            {"country": "Nepal","cityCode": "KTM","cityName": "Kathmandu"},
            {"country": "Indonesia","cityCode": "KDI","cityName": "Kendari"},
            {"country": "Indonesia","cityCode": "KRC","cityName": "Kerinci"},
            {"country": "Malaysia","cityCode": "KTE","cityName": "Kerteh"},
            {"country": "Indonesia","cityCode": "KTG","cityName": "Ketapang"},
            {"country": "Thailand","cityCode": "KKC","cityName": "Khon Kaen"},
            {"country": "India","cityCode": "COK","cityName": "Kochi"},
            {"country": "India","cityCode": "CCU","cityName": "Kolkata"},
            {"country": "Malaysia","cityCode": "KBR","cityName": "Kota Bharu"},
            {"country": "Malaysia","cityCode": "BKI","cityName": "Kota Kinabalu"},
            {"country": "Indonesia","cityCode": "KBU","cityName": "Kotabaru"},
            {"country": "Thailand","cityCode": "KBV","cityName": "Krabi"},
            {"country": "Malaysia","cityCode": "KUL","cityName": "Kuala Lumpur"},
            {"country": "Malaysia","cityCode": "TGG","cityName": "Kuala Terengganu"},
            {"country": "Malaysia","cityCode": "KCH","cityName": "Kuching"},
            {"country": "China","cityCode": "KMG","cityName": "Kunming"},
            {"country": "Indonesia","cityCode": "KOE","cityName": "Kupang"},
            {"country": "Malaysia","cityCode": "LBU","cityName": "Labuan"},
            {"country": "Indonesia","cityCode": "LAH","cityName": "Labuha"},
            {"country": "Indonesia","cityCode": "LBJ","cityName": "Labuan Bajo"},
            {"country": "Pakistan","cityCode": "LHE","cityName": "Lahore"},
            {"country": "Malaysia","cityCode": "LGK","cityName": "Langkawi"},
            {"country": "Indonesia","cityCode": "LKA","cityName": "Larantuka"},
            {"country": "Indonesia","cityCode": "LSW","cityName": "Lhokseumawe"},
            {"country": "Indonesia","cityCode": "LOP","cityName": "Lombok"},
            {"country": "United Kingdom","cityCode": "LHR","cityName": "London"},
            {"country": "Indonesia","cityCode": "LKI","cityName": "Lubuk Linggau"},
            {"country": "Indonesia","cityCode": "LUW","cityName": "Luwuk"},
            {"country": "Macau","cityCode": "MFM","cityName": "Macau"},
            {"country": "Saudi Arabia","cityCode": "MED","cityName": "Madinah"},
            {"country": "Indonesia","cityCode": "KJT","cityName": "Majalengka"},
            {"country": "Indonesia","cityCode": "MLG","cityName": "Malang"},
            {"country": "Indonesia","cityCode": "MWW","cityName": "Malinau"},
            {"country": "Indonesia","cityCode": "MJU","cityName": "Mamuju"},
            {"country": "Indonesia","cityCode": "MDC","cityName": "Manado"},
            {"country": "Indonesia","cityCode": "MKW","cityName": "Manokwari"},
            {"country": "Indonesia","cityCode": "AMI","cityName": "Mataram"},
            {"country": "Indonesia","cityCode": "MOF","cityName": "Maumere"},
            {"country": "Indonesia","cityCode": "MKF","cityName": "Mckenna AAF"},
            {"country": "Indonesia","cityCode": "MES","cityName": "Medan"},
            {"country": "Indonesia","cityCode": "KNO","cityName": "Medan Kuala Namu"},
            {"country": "Malaysia","cityCode": "MKZ","cityName": "Melaka"},
            {"country": "Indonesia","cityCode": "MNA","cityName": "Melanguane "},
            {"country": "Australia","cityCode": "MEL","cityName": "Melbourne"},
            {"country": "Indonesia","cityCode": "MKQ","cityName": "Merauke"},
            {"country": "Indonesia","cityCode": "MEQ","cityName": "Meulaboh"},
            {"country": "Indonesia","cityCode": "OTI","cityName": "Morotai"},
            {"country": "Indonesia","cityCode": "MOH","cityName": "Morowali"},
            {"country": "United States","cityCode": "MWS","cityName": "Muara Bungo"},
            {"country": "Indonesia","cityCode": "MPC","cityName": "Muko-Muko"},
            {"country": "India","cityCode": "BOM","cityName": "Mumbai"},
            {"country": "Indonesia","cityCode": "NBX","cityName": "Nabire"},
            {"country": "Japan","cityCode": "NGO","cityName": "Nagoya"},
            {"country": "Thailand","cityCode": "NST","cityName": "Nakhon Si Thammarat"},
            {"country": "Indonesia","cityCode": "NAM","cityName": "Namlea"},
            {"country": "China","cityCode": "KHN","cityName": "Nanchang"},
            {"country": "China","cityCode": "NNG","cityName": "Nanning"},
            {"country": "Indonesia","cityCode": "NTX","cityName": "Natuna Ranai"},
            {"country": "Indonesia","cityCode": "PDG","cityName": "Padang"},
            {"country": "Indonesia","cityCode": "AEG","cityName": "Padang Sidempuan"},
            {"country": "Indonesia","cityCode": "PXA","cityName": "Pagar Alam"},
            {"country": "Indonesia","cityCode": "PKY","cityName": "Palangkaraya"},
            {"country": "Indonesia","cityCode": "PLM","cityName": "Palembang"},
            {"country": "Indonesia","cityCode": "LLO","cityName": "Palopo"},
            {"country": "Indonesia","cityCode": "PLW","cityName": "Palu"},
            {"country": "Indonesia","cityCode": "PGK","cityName": "Pangkal Pinang"},
            {"country": "Indonesia","cityCode": "PKN","cityName": "Pangkalan Bun"},
            {"country": "Indonesia","cityCode": "PKU","cityName": "Pekanbaru"},
            {"country": "Malaysia","cityCode": "PEN","cityName": "Penang"},
            {"country": "Australia","cityCode": "PER","cityName": "Perth"},
            {"country": "Cambodia","cityCode": "PNH","cityName": "Phnom Penh"},
            {"country": "Thailand","cityCode": "HKT","cityName": "Phuket"},
            {"country": "Indonesia","cityCode": "PUM","cityName": "Pomalaa"},
            {"country": "Indonesia","cityCode": "PNK","cityName": "Pontianak"},
            {"country": "Indonesia","cityCode": "PSJ","cityName": "Poso"},
            {"country": "Indonesia","cityCode": "PSU","cityName": "Putus Sibau"},
            {"country": "Indonesia","cityCode": "RAQ","cityName": "Raha"},
            {"country": "Indonesia","cityCode": "RGT","cityName": "Rengat"},
            {"country": "Indonesia","cityCode": "RTI","cityName": "Roti"},
            {"country": "Indonesia","cityCode": "SRI","cityName": "Samarinda"},
            {"country": "Indonesia","cityCode": "SMQ","cityName": "Sampit"},
            {"country": "Indonesia","cityCode": "SQN","cityName": "Sanana"},
            {"country": "Malaysia","cityCode": "SDK","cityName": "Sandakan"},
            {"country": "United States","cityCode": "KSR","cityName": "Selayar"},
            {"country": "China","cityCode": "SYX","cityName": "Sanya"},
            {"country": "Japan","cityCode": "CTS","cityName": "New Chitose - Hokkaido"},
            {"country": "Indonesia","cityCode": "SXK","cityName": "Saumlaki"},
            {"country": "Indonesia","cityCode": "SRG","cityName": "Semarang"},
            {"country": "China","cityCode": "PVG","cityName": "Shanghai"},
            {"country": "China","cityCode": "SZX","cityName": "Shenzhen"},
            {"country": "Indonesia","cityCode": "FLZ","cityName": "Sibolga"},
            {"country": "Indonesia","cityCode": "DTB","cityName": "Silangit "},
            {"country": "Indonesia","cityCode": "SMG","cityName": "Simeulue"},
            {"country": "Singapore","cityCode": "SIN","cityName": "Singapore"},
            {"country": "Indonesia","cityCode": "SQG","cityName": "Sintang"},
            {"country": "Indonesia","cityCode": "SOC","cityName": "Solo"},
            {"country": "Indonesia","cityCode": "SOQ","cityName": "Sorong"},
            {"country": "Malaysia","cityCode": "SZB","cityName": "Subang"},
            {"country": "Indonesia","cityCode": "SWQ","cityName": "Sumbawa"},
            {"country": "Indonesia","cityCode": "SUP","cityName": "Sumenep"},
            {"country": "Indonesia","cityCode": "SUB","cityName": "Surabaya"},
            {"country": "Thailand","cityCode": "URT","cityName": "Surat Thani"},
            {"country": "Australia","cityCode": "SYD","cityName": "Sydney"},
            {"country": "Indonesia","cityCode": "NAH","cityName": "Tahuna"},
            {"country": "Taiwan","cityCode": "TPE","cityName": "Taipei"},
            {"country": "Indonesia","cityCode": "TXE","cityName": "Takengon"},
            {"country": "Indonesia","cityCode": "TMC","cityName": "Tambolaka"},
            {"country": "Indonesia","cityCode": "TJG","cityName": "Tanjung"},
            {"country": "Indonesia","cityCode": "TJQ","cityName": "Tanjung Pandan"},
            {"country": "Indonesia","cityCode": "TNJ","cityName": "Tanjung Pinang"},
            {"country": "Indonesia","cityCode": "TJS","cityName": "Tanjung Selor"},
            {"country": "Indonesia","cityCode": "TRK","cityName": "Tarakan"},
            {"country": "Indonesia","cityCode": "TSY","cityName": "Tasikmalaya"},
            {"country": "Malaysia","cityCode": "TWU","cityName": "Tawau"},
            {"country": "Indonesia","cityCode": "TTE","cityName": "Ternate"},
            {"country": "China","cityCode": "TSN","cityName": "Tianjin"},
            {"country": "Indonesia","cityCode": "TIM","cityName": "Timika"},
            {"country": "India","cityCode": "TRZ","cityName": "Tiruchirapally"},
            {"country": "Indonesia","cityCode": "KAZ","cityName": "Tobelo"},
            {"country": "Indonesia","cityCode": "TLI","cityName": "Toli-Toli"},
            {"country": "Thailand","cityCode": "TST","cityName": "Trang"},
            {"country": "India","cityCode": "TRV","cityName": "Thiruvananthapuram"},
            {"country": "Indonesia","cityCode": "LUV","cityName": "Tual"},
            {"country": "Thailand","cityCode": "UBP","cityName": "Ubon Ratchathani"},
            {"country": "Thailand","cityCode": "UTH","cityName": "Udon Thani"},
            {"country": "Indonesia","cityCode": "UPG","cityName": "Makassar"},
            {"country": "India","cityCode": "VNS","cityName": "Varanasi"},
            {"country": "Austria","cityCode": "VIE","cityName": "Vienna"},
            {"country": "India","cityCode": "VTZ","cityName": "Vishakhapatnam"},
            {"country": "Indonesia","cityCode": "WGP","cityName": "Waingapu"},
            {"country": "Indonesia","cityCode": "WNI","cityName": "Wakatobi"},
            {"country": "Indonesia","cityCode": "WMX","cityName": "Wamena"},
            {"country": "China","cityCode": "WUH","cityName": "Wuhan"},
            {"country": "China","cityCode": "XIY","cityName": "Xi'an"},
            {"country": "Indonesia","cityCode": "DEX","cityName": "Yahukimo"},
            {"country": "Myanmar","cityCode": "RGN","cityName": "Yangon"},
            {"country": "Indonesia","cityCode": "JOG","cityName": "Yogyakarta"},
            {"country": "China","cityCode": "CGO","cityName": "Zhengzhou"},
        ]
