#! /usr/bin/python3
# -*- coding: utf-8 -*-
"""Created on Fri May 10 03:47:45 UTC+8:00 2019
    镜像器用于存储稳定的数据, DD镜像器
written by pyGlenn.
"""


class CorpDDMirror:
    """DD镜像器
    """
    def __init__(self):
        self.logger: any = None  # 日志记录器
        # # # 国家三字码
        self._country_code: dict = {
                "DMK": "Bangkok (Don Mueang)",
                "BFV": "Buri Ram",
                "CNX": "Chiang Mai",
                "CEI": "Chiang Rai",
                "CJM": "Chumphon",
                "HDY": "Hat Yai",
                "KKC": "Khon Kaen",
                "KBV": "Krabi",
                "LPT": "Lampang",
                "LOE": "Loei",
                "HGN": "Mae Hong Son",
                "MAQ": "Mae Sot",
                "NST": "Nakhon Si Thammarat",
                "PHS": "Phitsanulok",
                "PRH": "Phrae",
                "HKT": "Phuket",
                "UNN": "Ranong",
                "SNO": "Sakon Nakhon",
                "URT": "Surat Thani",
                "TST": "Trang",
                "UBP": "Ubon Ratchathani",
                "UTH": "Udon Thani",
                "AM1": "Amnat Charoen",
                "CH1": "Chiang Rai (Chiang Khong)",
                "MI1": "Chiang Rai (Mae Sai)",
                "KB1": "Krabi (Ao Nang)",
                "NM1": "Krabi (Railay-Ao Nang pier)",
                "LN1": "Lamphun",
                "CK1": "Loei (Chiang Khan)",
                "MH1": "Mukdahan",
                "KP1": "Nakhon Phanom",
                "TN1": "Nakhon Phanom (That Phanom)",
                "KN1": "Nakhon Si Thammarat (Khanom)",
                "KW1": "Nakhon Si Thammarat (Kiriwong)",
                "TA1": "Nakhon Si Thammarat (Walailak Uni./Tha Sala) (Tha Sala)",
                "TS1": "Nakhon Si Thammarat (Thung Song)",
                "NI1": "Nong Khai",
                "KK1": "Phetchabun (Khao Kho)",
                "KT1": "Sakon Nakhon (Kham Takla)",
                "SW1": "Sakon Nakhon (Sawang Daen Din)",
                "WN1": "Sakon Nakhon (Wanon Niwat)",
                "ST1": "Sukhothai",
                "KS1": "Surat Thani (Khao Sok)",
                "RP1": "Surat Thani (Ratchaprapa Dam)",
                "SR1": "Surin",
                "UD1": "Uttaradit",
                "YS1": "Yasothon",
                "BL0": "Koh Bulone",
                "KD0": "Koh Kradan",
                "LT0": "Koh Lanta (Saladan pier)",
                "LL0": "Koh Laoliang",
                "LB0": "Koh Libong",
                "LP0": "Koh Lipe",
                "MK0": "Koh Mook",
                "NY0": "Koh Nangyuan",
                "NG0": "Koh Ngai",
                "TSP": "Koh Phangan (Tong Sala Pier)",
                "PP0": "Koh Phi Phi",
                "USM": "Koh Samui (Nar Ton Pier)",
                "TA0": "Koh Tao",
                "YN0": "Koh YaoNoi",
                "YY0": "Koh Yao Yai",
                "RB1": "Railay Beach",
                "CGO": "Zhengzhou, China",
                "CTU": "Chengdu, China",
                "NKG": "Nanjing, China",
                "NNG": "Nanning, China",
                "NTG": "Nantong, China",
                "TAO": "Qingdao, China",
                "TSN": "Tianjin, China",
                "PVG": "Shanghai, China",
                "SHE": "Shenyang, China",
                "XIY": "Xi'an Xianyang, China",
                "HET": "Hohhot Baita, China",
                "TPE": "Taipei, Taiwan",
                "MEL": "Melbourne, Australia",
                "OOL": "Gold Coast, Australia",
                "PER": "Perth, Australia",
                "SYD": "Sydney (Kingsford Smith)",
                "GAU": "Guwahati",
                "DEL": "New Delhi, India",
                "NRT": "Tokyo (Narita), Japan",
                "KIX": "Osaka (Kansai), Japan",
                "CTS": "Sapporo (Hokkaido), Japan",
                "VT1": "Vientiane",
                "RGN": "Yangon",
                "SIN": "Singapore",
                "ICN": "Incheon, South Korea",
                "SGN": "Ho Chi Minh"
            }
