#! /usr/bin/python3
# -*- coding: utf-8 -*-
"""Created on Fri May 10 03:47:45 UTC+8:00 2019
    镜像器用于存储稳定的数据, MM镜像器
written by pyleo.
"""


class PersMMMirror:
    """MM镜像器

    """
    
    def __init__(self):
        self.logger: any = None             # 日志记录器
        # # # 国家二字码
        self._default_nationality = {
            4: {'Code': 'AF', 'Name': 'Afghanistan'},
            8: {'Code': 'AL', 'Name': 'Albania'},
            90: {'Code': 'SB', 'Name': 'Solomon Islands'},
            12: {'Code': 'DZ', 'Name': 'Algeria'},
            16: {'Code': 'AS', 'Name': 'American Samoa'},
            20: {'Code': 'AD', 'Name': 'Andorra'},
            24: {'Code': 'AO', 'Name': 'Angola'},
            92: {'Code': 'VG', 'Name': 'British Virgin Islands'},
            96: {'Code': 'BN', 'Name': 'Brunei Darussalam'},
            28: {'Code': 'AG', 'Name': 'Antigua and Barbuda'},
            32: {'Code': 'AR', 'Name': 'Argentina'},
            51: {'Code': 'AM', 'Name': 'Armenia'},
            36: {'Code': 'AU', 'Name': 'Australia'},
            40: {'Code': 'AT', 'Name': 'Austria'},
            31: {'Code': 'AZ', 'Name': 'Azerbaijan'},
            44: {'Code': 'BS', 'Name': 'Bahamas'},
            48: {'Code': 'BH', 'Name': 'Bahrain'},
            50: {'Code': 'BD', 'Name': 'Bangladesh'},
            52: {'Code': 'BB', 'Name': 'Barbados'},
            56: {'Code': 'BE', 'Name': 'Belgium'},
            84: {'Code': 'BZ', 'Name': 'Belize'},
            60: {'Code': 'BM', 'Name': 'Bermuda'},
            64: {'Code': 'BT', 'Name': 'Bhutan'},
            68: {'Code': 'BO', 'Name': 'Bolivia (Plurinational State of)'},
            70: {'Code': 'BA', 'Name': 'Bosnia and Herzegovina'},
            72: {'Code': 'BW', 'Name': 'Botswana'},
            76: {'Code': 'BR', 'Name': 'Brazil'},
            533: {'Code': 'AW', 'Name': 'Aruba'},
            112: {'Code': 'BY', 'Name': 'Belarus'},
            204: {'Code': 'BJ', 'Name': 'Benin'},
            660: {'Code': 'AI', 'Name': 'Anguilla'},
            248: {'Code': 'AX', 'Name': 'Åland Islands'},
            392: {'Code': 'JP', 'Name': 'Japan'},
            100: {'Code': 'BG', 'Name': 'Bulgaria'},
            854: {'Code': 'BF', 'Name': 'Burkina Faso'},
            108: {'Code': 'BI', 'Name': 'Burundi'},
            116: {'Code': 'KH', 'Name': 'Cambodia'},
            120: {'Code': 'CM', 'Name': 'Cameroon'},
            124: {'Code': 'CA', 'Name': 'Canada'},
            132: {'Code': 'CV', 'Name': 'Cape Verde'},
            136: {'Code': 'KY', 'Name': 'Cayman Islands'},
            140: {'Code': 'CF', 'Name': 'Central African Republic'},
            148: {'Code': 'TD', 'Name': 'Chad'},
            152: {'Code': 'CL', 'Name': 'Chile'},
            156: {'Code': 'CN', 'Name': 'China'},
            446: {'Code': 'MO', 'Name': 'China, Macao Special Administrative Region'},
            170: {'Code': 'CO', 'Name': 'Colombia'},
            174: {'Code': 'KM', 'Name': 'Comoros'},
            178: {'Code': 'CG', 'Name': 'Congo'},
            184: {'Code': 'CK', 'Name': 'Cook Islands'},
            188: {'Code': 'CR', 'Name': 'Costa Rica'},
            384: {'Code': 'CI', 'Name': "Côte d'Ivoire"},
            191: {'Code': 'HR', 'Name': 'Croatia'},
            192: {'Code': 'CU', 'Name': 'Cuba'},
            196: {'Code': 'CY', 'Name': 'Cyprus'},
            203: {'Code': 'CZ', 'Name': 'Czech Republic'},
            408: {'Code': 'KP', 'Name': "Democratic People's Republic of Korea"},
            180: {'Code': 'CD', 'Name': 'Democratic Republic of the Congo'},
            208: {'Code': 'DK', 'Name': 'Denmark'},
            262: {'Code': 'DJ', 'Name': 'Djibouti'},
            212: {'Code': 'DM', 'Name': 'Dominica'},
            214: {'Code': 'DO', 'Name': 'Dominican Republic'},
            218: {'Code': 'EC', 'Name': 'Ecuador'},
            818: {'Code': 'EG', 'Name': 'Egypt'},
            222: {'Code': 'SV', 'Name': 'El Salvador'},
            226: {'Code': 'GQ', 'Name': 'Equatorial Guinea'},
            232: {'Code': 'ER', 'Name': 'Eritrea'},
            233: {'Code': 'EE', 'Name': 'Estonia'},
            231: {'Code': 'ET', 'Name': 'Ethiopia'},
            234: {'Code': 'FO', 'Name': 'Faeroe Islands'},
            238: {'Code': 'FK', 'Name': 'Falkland Islands (Malvinas)'},
            242: {'Code': 'FJ', 'Name': 'Fiji'},
            246: {'Code': 'FI', 'Name': 'Finland'},
            250: {'Code': 'FR', 'Name': 'France'},
            254: {'Code': 'GF', 'Name': 'French Guiana'},
            258: {'Code': 'PF', 'Name': 'French Polynesia'},
            266: {'Code': 'GA', 'Name': 'Gabon'},
            270: {'Code': 'GM', 'Name': 'Gambia'},
            268: {'Code': 'GE', 'Name': 'Georgia'},
            276: {'Code': 'DE', 'Name': 'Germany'},
            288: {'Code': 'GH', 'Name': 'Ghana'},
            292: {'Code': 'GI', 'Name': 'Gibraltar'},
            300: {'Code': 'GR', 'Name': 'Greece'},
            304: {'Code': 'GL', 'Name': 'Greenland'},
            308: {'Code': 'GD', 'Name': 'Grenada'},
            312: {'Code': 'GP', 'Name': 'Guadeloupe'},
            316: {'Code': 'GU', 'Name': 'Guam'},
            320: {'Code': 'GT', 'Name': 'Guatemala'},
            324: {'Code': 'GN', 'Name': 'Guinea'},
            624: {'Code': 'GW', 'Name': 'Guinea-Bissau'},
            328: {'Code': 'GY', 'Name': 'Guyana'},
            332: {'Code': 'HT', 'Name': 'Haiti'},
            336: {'Code': 'VA', 'Name': 'Holy See'},
            340: {'Code': 'HN', 'Name': 'Honduras'},
            344: {'Code': 'HK', 'Name': 'Hong Kong-China'},
            348: {'Code': 'HU', 'Name': 'Hungary'},
            352: {'Code': 'IS', 'Name': 'Iceland'},
            356: {'Code': 'IN', 'Name': 'India'},
            360: {'Code': 'ID', 'Name': 'Indonesia'},
            364: {'Code': 'IR', 'Name': 'Iran (Islamic Republic of)'},
            368: {'Code': 'IQ', 'Name': 'Iraq'},
            372: {'Code': 'IE', 'Name': 'Ireland'},
            833: {'Code': 'IM', 'Name': 'Isle of Man'},
            376: {'Code': 'IL', 'Name': 'Israel'},
            380: {'Code': 'IT', 'Name': 'Italy'},
            388: {'Code': 'JM', 'Name': 'Jamaica'},
            400: {'Code': 'JO', 'Name': 'Jordan'},
            398: {'Code': 'KZ', 'Name': 'Kazakhstan'},
            404: {'Code': 'KE', 'Name': 'Kenya'},
            296: {'Code': 'KI', 'Name': 'Kiribati'},
            414: {'Code': 'KW', 'Name': 'Kuwait'},
            417: {'Code': 'KG', 'Name': 'Kyrgyzstan'},
            418: {'Code': 'LA', 'Name': "Lao People's Democratic Republic"},
            428: {'Code': 'LV', 'Name': 'Latvia'},
            422: {'Code': 'LB', 'Name': 'Lebanon'},
            426: {'Code': 'LS', 'Name': 'Lesotho'},
            430: {'Code': 'LR', 'Name': 'Liberia'},
            434: {'Code': 'LY', 'Name': 'Libyan Arab Jamahiriya'},
            438: {'Code': 'LI', 'Name': 'Liechtenstein'},
            440: {'Code': 'LT', 'Name': 'Lithuania'},
            442: {'Code': 'LU', 'Name': 'Luxembourg'},
            807: {'Code': 'MK', 'Name': 'Macedonia (Republic of)'},
            450: {'Code': 'MG', 'Name': 'Madagascar'},
            454: {'Code': 'MW', 'Name': 'Malawi'},
            458: {'Code': 'MY', 'Name': 'Malaysia'},
            462: {'Code': 'MV', 'Name': 'Maldives'},
            466: {'Code': 'ML', 'Name': 'Mali'},
            470: {'Code': 'MT', 'Name': 'Malta'},
            584: {'Code': 'MH', 'Name': 'Marshall Islands'},
            474: {'Code': 'MQ', 'Name': 'Martinique'},
            478: {'Code': 'MR', 'Name': 'Mauritania'},
            480: {'Code': 'MU', 'Name': 'Mauritius'},
            484: {'Code': 'MX', 'Name': 'Mexico'},
            583: {'Code': 'FM', 'Name': 'Micronesia (Federated States of)'},
            492: {'Code': 'MC', 'Name': 'Monaco'},
            496: {'Code': 'MN', 'Name': 'Mongolia'},
            499: {'Code': 'ME', 'Name': 'Montenegro'},
            500: {'Code': 'MS', 'Name': 'Montserrat'},
            504: {'Code': 'MA', 'Name': 'Morocco'},
            508: {'Code': 'MZ', 'Name': 'Mozambique'},
            104: {'Code': 'MM', 'Name': 'Myanmar'},
            516: {'Code': 'NA', 'Name': 'Namibia'},
            520: {'Code': 'NR', 'Name': 'Nauru'},
            524: {'Code': 'NP', 'Name': 'Nepal'},
            528: {'Code': 'NL', 'Name': 'Netherlands'},
            530: {'Code': 'AN', 'Name': 'Netherlands Antilles'},
            540: {'Code': 'NC', 'Name': 'New Caledonia'},
            554: {'Code': 'NZ', 'Name': 'New Zealand'},
            558: {'Code': 'NI', 'Name': 'Nicaragua'},
            562: {'Code': 'NE', 'Name': 'Niger'},
            566: {'Code': 'NG', 'Name': 'Nigeria'},
            570: {'Code': 'NU', 'Name': 'Niue'},
            574: {'Code': 'NF', 'Name': 'Norfolk Island'},
            580: {'Code': 'MP', 'Name': 'Northern Mariana Islands'},
            578: {'Code': 'NO', 'Name': 'Norway'},
            512: {'Code': 'OM', 'Name': 'Oman'},
            586: {'Code': 'PK', 'Name': 'Pakistan'},
            585: {'Code': 'PW', 'Name': 'Palau'},
            275: {'Code': 'PS', 'Name': 'Palestinian Territory'},
            591: {'Code': 'PA', 'Name': 'Panama'},
            598: {'Code': 'PG', 'Name': 'Papua New Guinea'},
            600: {'Code': 'PY', 'Name': 'Paraguay'},
            604: {'Code': 'PE', 'Name': 'Peru'},
            608: {'Code': 'PH', 'Name': 'Philippines'},
            612: {'Code': 'PN', 'Name': 'Pitcairn'},
            616: {'Code': 'PL', 'Name': 'Poland'},
            620: {'Code': 'PT', 'Name': 'Portugal'},
            630: {'Code': 'PR', 'Name': 'Puerto Rico'},
            634: {'Code': 'QA', 'Name': 'Qatar'},
            410: {'Code': 'KR', 'Name': 'Republic of Korea'},
            498: {'Code': 'MD', 'Name': 'Republic of Moldova'},
            638: {'Code': 'RE', 'Name': 'Reunion'},
            642: {'Code': 'RO', 'Name': 'Romania'},
            643: {'Code': 'RU', 'Name': 'Russian Federation'},
            646: {'Code': 'RW', 'Name': 'Rwanda'},
            652: {'Code': 'BL', 'Name': 'Saint Barthelemy'},
            654: {'Code': 'SH', 'Name': 'Saint Helena'},
            659: {'Code': 'KN', 'Name': 'Saint Kitts and Nevis'},
            662: {'Code': 'LC', 'Name': 'Saint Lucia'},
            666: {'Code': 'PM', 'Name': 'Saint Pierre and Miquelon'},
            670: {'Code': 'VC', 'Name': 'Saint Vincent and the Grenadines'},
            882: {'Code': 'WS', 'Name': 'Samoa'},
            674: {'Code': 'SM', 'Name': 'San Marino'},
            678: {'Code': 'ST', 'Name': 'Sao Tome and Principe'},
            682: {'Code': 'SA', 'Name': 'Saudi Arabia'},
            686: {'Code': 'SN', 'Name': 'Senegal'},
            688: {'Code': 'RS', 'Name': 'Serbia'},
            690: {'Code': 'SC', 'Name': 'Seychelles'},
            694: {'Code': 'SL', 'Name': 'Sierra Leone'},
            702: {'Code': 'SG', 'Name': 'Singapore'},
            703: {'Code': 'SK', 'Name': 'Slovakia'},
            705: {'Code': 'SI', 'Name': 'Slovenia'},
            706: {'Code': 'SO', 'Name': 'Somalia'},
            710: {'Code': 'ZA', 'Name': 'South Africa'},
            724: {'Code': 'ES', 'Name': 'Spain'},
            144: {'Code': 'LK', 'Name': 'Sri Lanka'},
            736: {'Code': 'SD', 'Name': 'Sudan'},
            740: {'Code': 'SR', 'Name': 'Suriname'},
            744: {'Code': 'SJ', 'Name': 'Svalbard and Jan Mayen Islands'},
            748: {'Code': 'SZ', 'Name': 'Swaziland'},
            752: {'Code': 'SE', 'Name': 'Sweden'},
            756: {'Code': 'CH', 'Name': 'Switzerland'},
            760: {'Code': 'SY', 'Name': 'Syrian Arab Republic'},
            158: {'Code': 'TW', 'Name': 'Taiwan'},
            762: {'Code': 'TJ', 'Name': 'Tajikistan'},
            764: {'Code': 'TH', 'Name': 'Thailand'},
            626: {'Code': 'TL', 'Name': 'Timor-Leste'},
            768: {'Code': 'TG', 'Name': 'Togo'},
            772: {'Code': 'TK', 'Name': 'Tokelau'},
            776: {'Code': 'TO', 'Name': 'Tonga'},
            780: {'Code': 'TT', 'Name': 'Trinidad and Tobago'},
            788: {'Code': 'TN', 'Name': 'Tunisia'},
            792: {'Code': 'TR', 'Name': 'Turkey'},
            795: {'Code': 'TM', 'Name': 'Turkmenistan'},
            796: {'Code': 'TC', 'Name': 'Turks and Caicos Islands'},
            798: {'Code': 'TV', 'Name': 'Tuvalu'},
            800: {'Code': 'UG', 'Name': 'Uganda'},
            804: {'Code': 'UA', 'Name': 'Ukraine'},
            784: {'Code': 'AE', 'Name': 'United Arab Emirates'},
            826: {'Code': 'GB', 'Name': 'United Kingdom of Great Britain and Northern Ireland'},
            834: {'Code': 'TZ', 'Name': 'United Republic of Tanzania'},
            840: {'Code': 'US', 'Name': 'United States of America'},
            850: {'Code': 'VI', 'Name': 'United States Virgin Islands'},
            858: {'Code': 'UY', 'Name': 'Uruguay'},
            860: {'Code': 'UZ', 'Name': 'Uzbekistan'},
            548: {'Code': 'VU', 'Name': 'Vanuatu'},
            862: {'Code': 'VE', 'Name': 'Venezuela (Bolivarian Republic of)'},
            704: {'Code': 'VN', 'Name': 'Viet Nam'},
            876: {'Code': 'WF', 'Name': 'Wallis and Futuna Islands'},
            732: {'Code': 'EH', 'Name': 'Western Sahara'},
            887: {'Code': 'YE', 'Name': 'Yemen'},
            894: {'Code': 'ZM', 'Name': 'Zambia'},
            716: {'Code': 'ZW', 'Name': 'Zimbabwe'},
            8261: {'Code': 'G1', 'Name': 'British National Overseas'},
            8262: {'Code': 'G2', 'Name': 'British Overseas Citizen'},
            8263: {'Code': 'G3', 'Name': 'British Overseas Territories Citizen'},
            8264: {'Code': 'G4', 'Name': 'British Protected Person'},
            8265: {'Code': 'G5', 'Name': 'British Subject'}
        }

    def select_from_nationality(self, country_id: int=156) -> str:
        """选择国籍
        :param country_id:  国籍id号
        :return:  str
        """
        if type(country_id) is not int:
            self.logger.info(f"选择国籍非法传参(⊙﹏⊙)【{country_id}】")
            return ""

        for k, v in self._default_nationality.items():
            if k == country_id:
                return v['Code']
        return "CN"
